apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
data: 
  .env:
    REACT_APP_KAKAO_REDIRECT_URI=/login/kakao
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
        - name: frontend
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_dc7d1d6c6ec9